version: '3.8'

services:
  shagunpe-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/code
    restart: unless-stopped
