name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_DROPLET_SSH_KEY }}

      - name: Add droplet to known_hosts
        run: ssh-keyscan -H ${{ secrets.DO_DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Digital Ocean
        env:
          DO_DROPLET_IP: ${{ secrets.DO_DROPLET_IP }}
        run: |
          ssh root@${{ env.DO_DROPLET_IP }} << 'EOF'
            cd /root/shagunpe
            git pull origin main || git clone https://github.com/yourusername/shagunpe.git .
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker system prune -f
          EOF