name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DO_DROPLET_SSH_KEY }}" > ~/.ssh/sgnpe
          chmod 600 ~/.ssh/sgnpe
          cat >>~/.ssh/config <<END
          Host digitalocean
            HostName ${{ secrets.DO_DROPLET_IP }}
            User root
            IdentityFile ~/.ssh/sgnpe
            StrictHostKeyChecking no
          END

      - name: Deploy to Digital Ocean
        run: |
          ssh digitalocean << 'EOF'
            # Navigate to the project directory or clone the repo if not present
            cd /root/shagunpe || git clone https://github.com/inyourserve/shagunpe.git /root/shagunpe

            # Ensure the local branch is in sync with the remote
            git reset --hard origin/main

            # Debug step: Check if requirements.txt exists
            ls -la /root/shagunpe

            # Docker deployment steps
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker system prune -f
          EOF
