name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger the deploy on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH keys to access DigitalOcean
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DO_DROPLET_SSH_KEY }}" > ~/.ssh/sgnpe
          chmod 600 ~/.ssh/sgnpe
          cat >>~/.ssh/config <<END
          Host digitalocean
            HostName ${{ secrets.DO_DROPLET_IP }}
            User root
            IdentityFile ~/.ssh/sgnpe
            StrictHostKeyChecking no
          END

      # Step 3: Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        run: |
          ssh digitalocean << 'EOF'
            # Navigate to the project directory or clone the repository if not present
            if [ ! -d "/root/shagunpe" ]; then
              git clone https://github.com/inyourserve/shagunpe.git /root/shagunpe
            fi
            cd /root/shagunpe

            # Pull the latest changes from the main branch
            git reset --hard origin/main
            git pull origin main

            # List files to check if requirements.txt is present
            ls -la /root/shagunpe

            # Bring down any running containers
            docker-compose down

            # Build the Docker containers without cache
            docker-compose build --no-cache

            # Start the Docker containers in detached mode
            docker-compose up -d

            # Clean up unused Docker objects (optional)
            docker system prune -f
          EOF
