# .github/workflows/deploy.yml
name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DO_DROPLET_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host digitalocean
            HostName ${{ secrets.DO_DROPLET_IP }}
            User root
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy to Digital Ocean
        run: |
          ssh digitalocean << 'EOF'
            cd /root/shagunpe
            git pull origin main || git clone https://github.com/inyourserve/shagunpe.git .
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker system prune -f
          EOF