name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH keys to access DigitalOcean
      - name: Configure SSH
        env:
          DO_DROPLET_SSH_KEY: ${{ secrets.DO_DROPLET_SSH_KEY }}
          DO_DROPLET_IP: ${{ secrets.DO_DROPLET_IP }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DO_DROPLET_SSH_KEY" > ~/.ssh/sgnpe
          chmod 600 ~/.ssh/sgnpe
          cat >>~/.ssh/config <<END
          Host digitalocean
            HostName $DO_DROPLET_IP
            User root
            IdentityFile ~/.ssh/sgnpe
            StrictHostKeyChecking no
          END

      # Step 3: Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        env:
          DO_DROPLET_IP: ${{ secrets.DO_DROPLET_IP }}
        run: |
          ssh digitalocean << 'EOF'
            # Navigate to the project directory
            if [ ! -d "/root/shagunpe" ]; then
              # Clone the repository if it doesn't exist
              git clone https://github.com/inyourserve/shagunpe.git /root/shagunpe
            fi

            cd /root/shagunpe

            # Pull the latest changes from the main branch
            git fetch origin
            git reset --hard origin/main

            # Ensure requirements.txt exists
            if [ ! -f "/root/shagunpe/requirements.txt" ]; then
              echo "requirements.txt not found"
              exit 1
            fi

            # Stop and remove existing containers (if any)
            docker-compose down

            # Build Docker containers without cache
            docker-compose build --no-cache

            # Start Docker containers in detached mode
            docker-compose up -d

            # Clean up unused Docker objects (optional)
            docker system prune -f
          EOF
